Added printing of linsk slightly nicver:
apache-ivy                     FAILED https://koji.fedoraproject.org/koji/taskinfo?taskID=135214731
  * No match for argument: java-11-devel
  ** will fix it manually
  ** not sure how possible but seems ok up to f43 mass rebuild
bolzplatz2006                  FAILED https://koji.fedoraproject.org/koji/taskinfo?taskID=135214771
  * ../common_tools.h:64:15: note: ‘false’ is a keyword with ‘-std=c23’ onwards
  ** no op on my side
  ** seesm to be dead since f42 anyway
fop                            FAILED https://koji.fedoraproject.org/koji/taskinfo?taskID=135215087
  * [ERROR] /builddir/build/BUILD/fop-2.9-build/fop-2.9/fop-core/src/main/java/org/apache/fop/apps/FOUserAgent.java:[153,93] error: <anonymous org.apache.fop.apps.FOUserAgent$1> is not abstract and does not override abstract method getSourceResolution() in ImageSessionContext
  * [ERROR] /builddir/build/BUILD/fop-2.9-build/fop-2.9/fop-core/src/main/java/org/apache/fop/svg/AbstractFOPTranscoder.java:[258,69] error: <anonymous org.apache.fop.svg.AbstractFOPTranscoder$2> is not abstract and does not override abstract method getSourceResolution() in ImageSessionContext
  *[INFO] 2 errors
  ** will be reset back to 21 with bug
  ** seesm to be dead since f41 anyway
freemarker                     FAILED https://koji.fedoraproject.org/koji/taskinfo?taskID=135215788
  * No match for argument: java-1.8.0-openjdk
  * No match for argument: java-11-openjdk-devel
  ** will be fixed manually
  ** seesm to be dead since f41 anyway
IPAddress                      FAILED https://koji.fedoraproject.org/koji/taskinfo?taskID=135215882
  * No match for argument: java-11-openjdk-devel
  ** will be fixed manually
  ** seesm to be dead since f42 anyway
javapoet                       FAILED https://koji.fedoraproject.org/koji/taskinfo?taskID=135216160
  * [WARNING] [options] bootstrap class path is not set in conjunction with -source 7
  ** will be reseet back to 21 with bug
  ** seesm to be dead since f41 anyway
jedit                          FAILED https://koji.fedoraproject.org/koji/taskinfo?taskID=135216199
  * [javac] error: release version 11 not supported
  ** will be reseet back to 21 with bug
juniversalchardet              FAILED https://koji.fedoraproject.org/koji/taskinfo?taskID=135216314
  * [WARNING] [options] bootstrap class path is not set in conjunction with -source 7
  ** will be reseet back to 21 with bug
  ** seesm to be dead since f41 anyway
vecmath1.2                     running? https://koji.fedoraproject.org/koji/taskinfo?taskID=135221618
  * Not sure what happened here, seesm like not running at all.

ant-contrib                    passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135214700
antlrworks                     passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135214723
apache-ivy                     FAILED https://koji.fedoraproject.org/koji/taskinfo?taskID=135214731
beansbinding                   passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135214761
bolzplatz2006                  FAILED https://koji.fedoraproject.org/koji/taskinfo?taskID=135214771
brazil                         passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135214818
bsh                            passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135214852
byteman                        passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135214867
cambozola                      passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135214873
CardManager                    passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135214879
CFR                            passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135214887
colossus                       passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135214896
console-image-viewer           passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135214914
cortado                        passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135214920
ditaa                          passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135214948
dom4j                          passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135214957
eclipse-swt                    passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135214990
fernflower                     passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135215013
flute                          passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135215050
fop                            FAILED https://koji.fedoraproject.org/koji/taskinfo?taskID=135215087
freecol                        passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135215781
freemarker                     FAILED https://koji.fedoraproject.org/koji/taskinfo?taskID=135215788
freerouting                    passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135215823
hid4java                       passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135215835
icedtea-web                    passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135215846
imagej                         passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135215859
IPAddress                      FAILED https://koji.fedoraproject.org/koji/taskinfo?taskID=135215882
javapackages-bootstrap         passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216147
javapoet                       FAILED https://koji.fedoraproject.org/koji/taskinfo?taskID=135216160
jcip-annotations               passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216176
jcuber                         passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216191
jedit                          FAILED https://koji.fedoraproject.org/koji/taskinfo?taskID=135216199
jFormatString                  passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216217
jigawatts                      passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216239
jorbis                         passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216256
jpanoramamaker                 passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216282
jssc                           passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216301
juniversalchardet              FAILED https://koji.fedoraproject.org/koji/taskinfo?taskID=135216314
libbase                        passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216377
libfonts                       passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216405
libformula                     passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216425
liblayout                      passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216444
libloader                      passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216468
librepository                  passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216496
libserializer                  passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216519
libvirt-java                   passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216527
Mars                           passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216540
mecab-java                     passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216547
miglayout                      passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216562
mp                             passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216568
mysql-connector-java           passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216601
octave                         passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216618
openjdk-asmtools               passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216632
openjfx                        passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216724
OpenStego                      passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135216736
parserng                       passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135218084
pdftk-java                     passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135218105
pentaho-libxml                 passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135218156
pentaho-reporting-flow-engine  passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135218461
plantuml                       passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135218495
procyon                        passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135218656
regexp                         passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135218915
rhino                          passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135219024
R-rJava                        passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135220040
rsyntaxtextarea                passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135220103
sblim-cim-client2              passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135220863
sblim-cim-client               passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135220568
sdljava                        passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135220938
stringtemplate                 passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135221252
swing-layout                   passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135221273
t-digest                       passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135221346
tomcat                         passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135221528
vecmath1.2                     running? https://koji.fedoraproject.org/koji/taskinfo?taskID=135221618
voms-clients-java              passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135221821
xmvn-generator                 passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135221854
xmvn                           passed! https://koji.fedoraproject.org/koji/taskinfo?taskID=135221845